export enum PaymentStatus {
  INITIATED,
  THREEDS_AUTHENTICATION_SUCCESSFUL,
  THREEDS_AUTHENTICATION_REJECTED,
  THREEDS_AUTHENTICATION_ERROR,
  THREEDS_CHALLENGE_SUCCESSFUL,
  THREEDS_CHALLENGE_UNSUCCESSFUL,
  THREEDS_CHALLENGE_ERROR,
  AUTHORIZATION_SUCCESSFUL,
  AUTHORIZATION_REJECTED,
  AUTHORIZATION_ERROR,
}
